---
language: ruby
sudo: false
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
notifications:
  email: false
env:
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 4.1.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
script:
  - puppet-lint --no-80chars-check --no-autoloader_layout-check .
  - find . -name *.pp | xargs puppet parser validate
